// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBZ2UO5V0VbfpFKsuEdt-JCvUJxv5WGU',
    appId: '1:39536504302:web:a569e2926485a536bb72ff',
    messagingSenderId: '39536504302',
    projectId: 'beautyblendr-5b2d6',
    authDomain: 'beautyblendr-5b2d6.firebaseapp.com',
    databaseURL: 'https://beautyblendr-5b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beautyblendr-5b2d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf2GnCkI9zzFjjewoTWqjjceoH9GUi6a8',
    appId: '1:39536504302:android:98d7a7692c336bf5bb72ff',
    messagingSenderId: '39536504302',
    projectId: 'beautyblendr-5b2d6',
    databaseURL: 'https://beautyblendr-5b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beautyblendr-5b2d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsg_DbsjU-UHu8YQDt6cPSOlcCd4x9kQ',
    appId: '1:39536504302:ios:f0538663802e4ddfbb72ff',
    messagingSenderId: '39536504302',
    projectId: 'beautyblendr-5b2d6',
    databaseURL: 'https://beautyblendr-5b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beautyblendr-5b2d6.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTsg_DbsjU-UHu8YQDt6cPSOlcCd4x9kQ',
    appId: '1:39536504302:ios:a3cd695b987a7f6abb72ff',
    messagingSenderId: '39536504302',
    projectId: 'beautyblendr-5b2d6',
    databaseURL: 'https://beautyblendr-5b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beautyblendr-5b2d6.appspot.com',
    iosBundleId: 'com.example.demodemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUBZ2UO5V0VbfpFKsuEdt-JCvUJxv5WGU',
    appId: '1:39536504302:web:a569e2926485a536bb72ff',
    messagingSenderId: '39536504302',
    projectId: 'beautyblendr-5b2d6',
    authDomain: 'beautyblendr-5b2d6.firebaseapp.com',
    databaseURL: 'https://beautyblendr-5b2d6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beautyblendr-5b2d6.appspot.com',
  );
}